version: '3'
services:
  eleventy:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ..:/code
    # tty: true
